DROP DATABASE IF EXISTS ecommerce;
CREATE DATABASE IF NOT EXISTS ecommerce;

DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS users (
    id int UNSIGNED NOT NULL AUTO_INCREMENT,
    dni varchar(9) NOT NULL UNIQUE,
    name varchar(100) NOT NULL,
    surname varchar(100) NOT NULL,
    email varchar(255) NOT NULL UNIQUE,
    role varchar(5) NOT NULL DEFAULT 'user',
    password varchar(255) NOT NULL,
    banned tinyint(1),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS products;
CREATE TABLE IF NOT EXISTS products (
    id int UNSIGNED NOT NULL AUTO_INCREMENT,
    title varchar(100) NOT NULL,
    description text(1000),
    price int NOT NULL DEFAULT 0,
    discount int DEFAULT NULL,
    stock int NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS products_photos;
CREATE TABLE IF NOT EXISTS products_photos (
    id int UNSIGNED NOT NULL AUTO_INCREMENT,
    image varchar(255) NOT NULL,
    products_id INT UNSIGNED NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (products_id)
    REFERENCES products (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS categories;
CREATE TABLE IF NOT EXISTS categories (
    id int UNSIGNED NOT NULL AUTO_INCREMENT,
    name varchar(30) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS products_has_categories;
CREATE TABLE IF NOT EXISTS products_has_categories (
    id int UNSIGNED NOT NULL AUTO_INCREMENT,
    products_id INT UNSIGNED NOT NULL,
    categories_id INT UNSIGNED NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (products_id)
    REFERENCES products (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY (categories_id)
    REFERENCES categories (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)ENGINE=INNODB DEFAULT CHARSET=utf8;